#include "../include/segy/segy.hpp"
#include <iostream>
#include <cmath>

/// @brief Simple SEG-Y writer example
/// Creates a synthetic SEG-Y file with sine wave data

int main() {
    const char* output_file = "/tmp/synthetic.segy";

    try {
        std::cout << "🔨 Creating synthetic SEG-Y file...\n\n";

        // Create textual header
        segy::TextualHeader textual;
        textual.set_line(1, "C01 SYNTHETIC SEG-Y FILE");
        textual.set_line(2, "C02 Generated by SEG-Y library example");
        textual.set_line(3, "C03 Contains synthetic sine wave data");
        textual.set_line(4, "C04 10 traces, 100 samples each");
        textual.set_line(5, "C05 Sample interval: 4000 microseconds (4ms)");
        textual.set_line(40, "C40 END TEXTUAL HEADER");

        // Create binary header
        segy::BinaryHeader binary;
        binary.set_job_id(99999);
        binary.set_line_number(1);
        binary.set_reel_number(1);
        binary.set_sample_interval(4000); // 4ms
        binary.set_samples_per_trace(100);
        binary.set_sample_format(segy::SampleFormat::IEEEFloat);

        std::cout << "📝 Textual Header: Set (40 lines)\n";
        std::cout << "🔧 Binary Header:\n";
        std::cout << "   Sample Interval: 4000 µs\n";
        std::cout << "   Samples/Trace:   100\n";
        std::cout << "   Format:          IEEE Float\n\n";

        // Create writer
        segy::Writer<float> writer(output_file, textual, binary);

        // Generate 10 traces with different frequency sine waves
        const size_t num_traces = 10;
        const size_t samples_per_trace = 100;

        std::cout << "📈 Generating " << num_traces << " traces...\n";

        for (size_t t = 0; t < num_traces; ++t) {
            // Create trace header
            segy::TraceHeader trace_header;
            trace_header.set_trace_sequence(static_cast<int32_t>(t + 1));
            trace_header.set_inline_number(100 + static_cast<int32_t>(t));
            trace_header.set_crossline_number(200);
            trace_header.set_num_samples(static_cast<int16_t>(samples_per_trace));
            trace_header.set_sample_interval(4000);

            // Create trace
            segy::Trace<float> trace(trace_header, samples_per_trace);
            auto samples = trace.samples();

            // Generate sine wave with increasing frequency
            const float frequency = 1.0f + static_cast<float>(t) * 0.5f;
            const float amplitude = 1000.0f;

            for (size_t i = 0; i < samples_per_trace; ++i) {
                float t_val = static_cast<float>(i) / static_cast<float>(samples_per_trace);
                samples[i] = amplitude * std::sin(2.0f * 3.14159f * frequency * t_val);
            }

            writer.write_trace(trace);

            std::cout << "   Trace " << (t + 1) << " written "
                     << "(freq=" << frequency << " Hz)\n";
        }

        writer.close();

        std::cout << "\n✅ File created successfully: " << output_file << "\n";
        std::cout << "   Total traces: " << num_traces << "\n";
        std::cout << "   File size: ~" << ((3200 + 400 + num_traces * (240 + 100 * 4)) / 1024)
                 << " KB\n";

    } catch (const std::exception& e) {
        std::cerr << "❌ Error: " << e.what() << "\n";
        return 1;
    }

    return 0;
}
